version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "./examples/**/*"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
    groups:
      react-router:
        patterns:
          - "@react-router/*"
          - "react-router"
          - "react-router-dom"